'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  addTorrent:        (src, resumePos, episodeContext) => ipcRenderer.invoke('torrent:add', src, resumePos, episodeContext),
  changeFile:        (id, idx)    => ipcRenderer.invoke('torrent:changeFile', id, idx),
  playTorrent:       (id)         => ipcRenderer.invoke('torrent:play', id),
  playLocal:         (id)         => ipcRenderer.invoke('torrent:playLocal', id),
  stopSeed:          (id)         => ipcRenderer.invoke('torrent:stopSeed', id),
  removeTorrent:     (id)         => ipcRenderer.invoke('torrent:remove', id),
  retryTorrent:      (id)         => ipcRenderer.invoke('torrent:retry', id),
  reorderQueue:      (order)      => ipcRenderer.invoke('queue:reorder', order),
  getHistory:        ()           => ipcRenderer.invoke('history:get'),
  fetchHistoryMeta:  (id, name)   => ipcRenderer.invoke('history:fetchMeta', id, name),
  removeHistory:     (id)         => ipcRenderer.invoke('history:remove', id),
  followList:        ()           => ipcRenderer.invoke('follow:list'),
  followAdd:         (item)       => ipcRenderer.invoke('follow:add', item),
  followRemove:      (imdbId)     => ipcRenderer.invoke('follow:remove', imdbId),
  followCheck:       ()           => ipcRenderer.invoke('follow:check'),
  followGrab:        (imdbId)     => ipcRenderer.invoke('follow:grab', imdbId),
  onNewEpisode:      (cb)         => ipcRenderer.on('follow:newEpisode', (_, data) => cb(data)),
  discoverDevices:   ()               => ipcRenderer.invoke('cast:discover'),
  castToDevice:      (id, host, type) => ipcRenderer.invoke('cast:play', id, host, type),
  seriesEpisodes:    (imdbId, tvmazeId) => ipcRenderer.invoke('series:episodes', imdbId, tvmazeId),
  seriesProgress:    (imdbId)       => ipcRenderer.invoke('series:progress', imdbId),
  seriesMarkWatched: (imdbId, s, e, w) => ipcRenderer.invoke('series:markWatched', imdbId, s, e, w),
  getSettings:       ()           => ipcRenderer.invoke('settings:get'),
  saveSettings:      (s)          => ipcRenderer.invoke('settings:save', s),
  detectPlayers:     ()           => ipcRenderer.invoke('players:detect'),
  openTorrentDialog: ()           => ipcRenderer.invoke('dialog:torrent'),
  openPlayerDialog:  ()           => ipcRenderer.invoke('dialog:player'),
  openDirDialog:     ()           => ipcRenderer.invoke('dialog:directory'),
  discoverFetch:     (cat, page)  => ipcRenderer.invoke('discover:fetch', cat, page),
  metaDetail:        (imdbId, type) => ipcRenderer.invoke('meta:detail', imdbId, type),
  torrentioSearch:   (query, type)                  => ipcRenderer.invoke('torrentio:search', query, type),
  torrentioStreams:  (id, type, season, episode)     => ipcRenderer.invoke('torrentio:streams', id, type, season, episode),
  onState:           (cb)         => ipcRenderer.on('torrent:state', (_, data) => cb(data)),
  onClipboardMagnet: (cb)         => ipcRenderer.on('clipboard:magnet', (_, magnet) => cb(magnet)),
  onNextEpisode:     (cb)         => ipcRenderer.on('episode:next', (_, data) => cb(data)),
  // Window controls
  minimize:          ()           => ipcRenderer.send('window:minimize'),
  maximize:          ()           => ipcRenderer.send('window:maximize'),
  close:             ()           => ipcRenderer.send('window:close'),
  isMaximized:       ()           => ipcRenderer.invoke('window:isMaximized'),
  onMaximize:        (cb)         => ipcRenderer.on('window:maximize',   () => cb(true)),
  onUnmaximize:      (cb)         => ipcRenderer.on('window:unmaximize', () => cb(false)),
  onUpdateAvailable: (cb)         => ipcRenderer.on('update:available',  (_, data) => cb(data)),
  onUpdateProgress:  (cb)         => ipcRenderer.on('update:progress',   (_, data) => cb(data)),
  downloadUpdate:    ()           => ipcRenderer.invoke('update:download'),
  openRelease:       (url)        => ipcRenderer.send('update:openRelease', url),
  getVersion:        ()           => ipcRenderer.invoke('app:version'),
  openExternal:      (url)        => ipcRenderer.send('app:openExternal', url),
});
